
@BASE_URL=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjE1LCJpYXQiOjE3MTcyNTIzNzksImV4cCI6MTcxNzI1MjQzOX0.9Bgy0-kQ5MQdNo0VbCOEFR05KAD1lNw9GLmnjthEUbA
### check connection
GET {{BASE_URL}} HTTP/1.1

### create user
POST {{BASE_URL}}/api/users HTTP/1.1
content-type: application/json

{
    "first_name": "daniel",
    "last_name": "wid",
    "email": "daniel3@gmail.com",
    "password": "1q@2w3E4R"
}

### login
POST {{BASE_URL}}/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "daniel3@gmail.com",
    "password": "1q@2w3E4R"
}

### getUserById
GET {{BASE_URL}}/api/users/15 HTTP/1.1
Authorization: {{TOKEN}}
content-type: application/json

